2017-12-23 13:00:04,036 [main] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Valid utc time ranges are dictated by clockService as follows:
2017-12-23 13:00:04,038 [main] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - APPLICABLE_START_TIME=2000-001T11:58:55.816, APPLICABLE_STOP_TIME=2017-360T19:17:40.149
2017-12-23 13:00:04,038 [main] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Given UTC = 2016-08-26~23:53:00
2017-12-23 13:00:04,038 [main] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Please ensure that positionSensor and sclk are synchronized
2017-12-23 13:00:04,050 [main] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Curiosity internal spacecraft clock started at :: 2016-08-27T04:53:00.000Z
2017-12-23 13:00:04,050 [main] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Mission duration is set to :: 1 year(s).
2017-12-23 13:00:04,050 [main] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Mission duration = 31536000000
2017-12-23 13:00:08,174 [main] INFO space.exploration.mars.rover.diagnostics.RoverGarbageCollector  - Starting garbageCollection
2017-12-23 13:00:10,174 [main] INFO space.exploration.mars.rover.kernel.Rover  - Rover current position is = java.awt.Point[x=525,y=100]
2017-12-23 13:00:11,175 [main] INFO space.exploration.mars.rover.sensor.Lidar  - Lidar initialized and ready!
2017-12-23 13:00:12,176 [main] INFO space.exploration.mars.rover.sensor.Spectrometer  - Spectrometer initialized and ready!
2017-12-23 13:00:13,374 [main] INFO space.exploration.mars.rover.sensor.Camera  - Camera initialized and ready!
2017-12-23 13:00:14,378 [main] INFO space.exploration.mars.rover.sensor.Radar  - Radar configured:: 
2017-12-23 13:00:15,793 [main] INFO space.exploration.mars.rover.power.Battery  - Battery configured, batteryLife:primaryPowerUnits = 1200 auxiliaryPowerUnits = 100 alertThreshold: 100 rechargeTime = 60000
2017-12-23 13:00:16,795 [main] INFO space.exploration.mars.rover.kernel.Rover  - Battery Monitor configured!
2017-12-23 13:00:16,809 [main] INFO org.apache.kafka.clients.producer.ProducerConfig  - ProducerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [localhost:9092]
	ssl.keystore.type = JKS
	sasl.mechanism = GSSAPI
	max.block.ms = 60000
	interceptor.classes = null
	ssl.truststore.password = null
	client.id = 
	ssl.endpoint.identification.algorithm = null
	request.timeout.ms = 30000
	acks = 1
	receive.buffer.bytes = 32768
	ssl.truststore.type = JKS
	retries = 0
	ssl.truststore.location = null
	ssl.keystore.password = null
	send.buffer.bytes = 131072
	compression.type = none
	metadata.fetch.timeout.ms = 60000
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	batch.size = 16384
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	linger.ms = 0

2017-12-23 13:00:16,887 [main] INFO org.apache.kafka.clients.producer.ProducerConfig  - ProducerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [localhost:9092]
	ssl.keystore.type = JKS
	sasl.mechanism = GSSAPI
	max.block.ms = 60000
	interceptor.classes = null
	ssl.truststore.password = null
	client.id = producer-1
	ssl.endpoint.identification.algorithm = null
	request.timeout.ms = 30000
	acks = 1
	receive.buffer.bytes = 32768
	ssl.truststore.type = JKS
	retries = 0
	ssl.truststore.location = null
	ssl.keystore.password = null
	send.buffer.bytes = 131072
	compression.type = none
	metadata.fetch.timeout.ms = 60000
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	batch.size = 16384
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	linger.ms = 0

2017-12-23 13:00:16,887 [main] WARN org.apache.kafka.clients.producer.ProducerConfig  - The configuration zookeeper.connect = localhost:2181 was supplied but isn't a known config.
2017-12-23 13:00:16,887 [main] WARN org.apache.kafka.clients.producer.ProducerConfig  - The configuration group.id = space.exploration.mars.rover.curiosity.1514055602956 was supplied but isn't a known config.
2017-12-23 13:00:16,887 [main] WARN org.apache.kafka.clients.producer.ProducerConfig  - The configuration source.topic = earth_to_curiosity_5 was supplied but isn't a known config.
2017-12-23 13:00:16,887 [main] WARN org.apache.kafka.clients.producer.ProducerConfig  - The configuration auto.offset.reset = largest was supplied but isn't a known config.
2017-12-23 13:00:16,887 [main] WARN org.apache.kafka.clients.producer.ProducerConfig  - The configuration metadata.broker.list = localhost:9092 was supplied but isn't a known config.
2017-12-23 13:00:16,888 [main] WARN org.apache.kafka.clients.producer.ProducerConfig  - The configuration destination.topic = curiosity_to_earth_5 was supplied but isn't a known config.
2017-12-23 13:00:16,889 [main] INFO org.apache.kafka.common.utils.AppInfoParser  - Kafka version : 0.10.0.1
2017-12-23 13:00:16,889 [main] INFO org.apache.kafka.common.utils.AppInfoParser  - Kafka commitId : a7a17cdec9eaa6c5
2017-12-23 13:00:17,006 [main] INFO kafka.utils.VerifiableProperties  - Verifying properties
2017-12-23 13:00:17,031 [main] INFO kafka.utils.VerifiableProperties  - Property auto.offset.reset is overridden to largest
2017-12-23 13:00:17,032 [main] WARN kafka.utils.VerifiableProperties  - Property bootstrap.servers is not valid
2017-12-23 13:00:17,032 [main] WARN kafka.utils.VerifiableProperties  - Property destination.topic is not valid
2017-12-23 13:00:17,032 [main] INFO kafka.utils.VerifiableProperties  - Property group.id is overridden to space.exploration.mars.rover.curiosity.1514055602956
2017-12-23 13:00:17,032 [main] WARN kafka.utils.VerifiableProperties  - Property key.serializer is not valid
2017-12-23 13:00:17,032 [main] WARN kafka.utils.VerifiableProperties  - Property metadata.broker.list is not valid
2017-12-23 13:00:17,032 [main] WARN kafka.utils.VerifiableProperties  - Property source.topic is not valid
2017-12-23 13:00:17,032 [main] WARN kafka.utils.VerifiableProperties  - Property value.serializer is not valid
2017-12-23 13:00:17,032 [main] INFO kafka.utils.VerifiableProperties  - Property zookeeper.connect is overridden to localhost:2181
2017-12-23 13:00:17,068 [main] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], Connecting to zookeeper instance at localhost:2181
2017-12-23 13:00:17,075 [ZkClient-EventThread-28-localhost:2181] INFO org.I0Itec.zkclient.ZkEventThread  - Starting ZkClient event thread.
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:host.name=zion-mainframe
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:java.version=1.8.0_151
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:java.vendor=Oracle Corporation
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:java.class.path=target/mars.rover-1.3-SOLSHOT-shaded.jar
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:java.library.path=$LD_LIBRARY_PATH:"/home/sanket/Documents/workspace/SpiceUtilities/src/main/resources/JNISpice/lib/libJNISpice.so":/home/sanket/Documents/workspace/SpiceUtilities/src/main/resources/JNISpice/lib/libJNISpice.so:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:java.io.tmpdir=/tmp
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:java.compiler=<NA>
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:os.name=Linux
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:os.arch=amd64
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:os.version=4.10.0-42-generic
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:user.name=sanket
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:user.home=/home/sanket
2017-12-23 13:00:17,079 [main] INFO org.apache.zookeeper.ZooKeeper  - Client environment:user.dir=/home/sanket/Documents/workspace/MarsRover/mars.rover
2017-12-23 13:00:17,080 [main] INFO org.apache.zookeeper.ZooKeeper  - Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@26794848
2017-12-23 13:00:17,089 [main] INFO org.I0Itec.zkclient.ZkClient  - Waiting for keeper state SyncConnected
2017-12-23 13:00:17,092 [main-SendThread(localhost:2181)] INFO org.apache.zookeeper.ClientCnxn  - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-12-23 13:00:17,164 [main-SendThread(localhost:2181)] INFO org.apache.zookeeper.ClientCnxn  - Socket connection established to localhost/127.0.0.1:2181, initiating session
2017-12-23 13:00:17,171 [main-SendThread(localhost:2181)] INFO org.apache.zookeeper.ClientCnxn  - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x160431894db0047, negotiated timeout = 6000
2017-12-23 13:00:17,172 [main-EventThread] INFO org.I0Itec.zkclient.ZkClient  - zookeeper state changed (SyncConnected)
2017-12-23 13:00:17,179 [main] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], starting auto committer every 60000 ms
2017-12-23 13:00:17,195 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], begin registering consumer space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6 in ZK
2017-12-23 13:00:17,215 [Thread-2] INFO kafka.utils.ZKCheckedEphemeral  - Creating /consumers/space.exploration.mars.rover.curiosity.1514055602956/ids/space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6 (is it secure? false)
2017-12-23 13:00:17,227 [Thread-2] INFO kafka.utils.ZKCheckedEphemeral  - Result of znode creation is: OK
2017-12-23 13:00:17,227 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], end registering consumer space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6 in ZK
2017-12-23 13:00:17,230 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6_watcher_executor] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], starting watcher executor thread for consumer space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6
2017-12-23 13:00:17,245 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], begin rebalancing consumer space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6 try #0
2017-12-23 13:00:17,318 [Thread-2] INFO kafka.consumer.ConsumerFetcherManager  - [ConsumerFetcherManager-1514055617177] Stopping leader finder thread
2017-12-23 13:00:17,319 [Thread-2] INFO kafka.consumer.ConsumerFetcherManager  - [ConsumerFetcherManager-1514055617177] Stopping all fetchers
2017-12-23 13:00:17,319 [Thread-2] INFO kafka.consumer.ConsumerFetcherManager  - [ConsumerFetcherManager-1514055617177] All connections stopped
2017-12-23 13:00:17,320 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], Cleared all relevant queues for this fetcher
2017-12-23 13:00:17,320 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], Cleared the data chunks in all the consumer message iterators
2017-12-23 13:00:17,320 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], Committing all offsets after clearing the fetcher queues
2017-12-23 13:00:17,321 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], Releasing partition ownership
2017-12-23 13:00:17,342 [Thread-2] INFO kafka.consumer.RangeAssignor  - Consumer space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6 rebalancing the following partitions: ArrayBuffer(0) for topic earth_to_curiosity_5 with consumers: List(space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-0)
2017-12-23 13:00:17,343 [Thread-2] INFO kafka.consumer.RangeAssignor  - space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-0 attempting to claim partition 0
2017-12-23 13:00:17,364 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-0 successfully owned partition 0 for topic earth_to_curiosity_5
2017-12-23 13:00:17,373 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], Consumer space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6 selected partitions : earth_to_curiosity_5:0: fetched offset = -1: consumed offset = -1
2017-12-23 13:00:17,376 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.consumer.ConsumerFetcherManager$LeaderFinderThread  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread], Starting 
2017-12-23 13:00:17,376 [Thread-2] INFO kafka.consumer.ZookeeperConsumerConnector  - [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6], end rebalancing consumer space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6 try #0
2017-12-23 13:00:17,392 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.utils.VerifiableProperties  - Verifying properties
2017-12-23 13:00:17,392 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.utils.VerifiableProperties  - Property client.id is overridden to space.exploration.mars.rover.curiosity.1514055602956
2017-12-23 13:00:17,392 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.utils.VerifiableProperties  - Property metadata.broker.list is overridden to zion-mainframe:9092
2017-12-23 13:00:17,393 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.utils.VerifiableProperties  - Property request.timeout.ms is overridden to 30000
2017-12-23 13:00:17,402 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.client.ClientUtils$  - Fetching metadata from broker BrokerEndPoint(0,zion-mainframe,9092) with correlation id 0 for 1 topic(s) Set(earth_to_curiosity_5)
2017-12-23 13:00:17,406 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.producer.SyncProducer  - Connected to zion-mainframe:9092 for producing
2017-12-23 13:00:17,415 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.producer.SyncProducer  - Disconnecting from zion-mainframe:9092
2017-12-23 13:00:17,428 [ConsumerFetcherThread-space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-0-0] INFO kafka.consumer.ConsumerFetcherThread  - [ConsumerFetcherThread-space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-0-0], Starting 
2017-12-23 13:00:17,442 [space.exploration.mars.rover.curiosity.1514055602956_zion-mainframe-1514055617067-38f358d6-leader-finder-thread] INFO kafka.consumer.ConsumerFetcherManager  - [ConsumerFetcherManager-1514055617177] Added fetcher for partitions ArrayBuffer([[earth_to_curiosity_5,0], initOffset -1 to broker BrokerEndPoint(0,zion-mainframe,9092)] )
2017-12-23 13:00:18,181 [main] INFO space.exploration.mars.rover.communication.Radio  - Radio configured:: 
group.id::space.exploration.mars.rover.curiosity.1514055602956
auto.offset.reset::largest
bootstrap.servers::localhost:9092
value.serializer::org.apache.kafka.common.serialization.ByteArraySerializer
destination.topic::curiosity_to_earth_5
zookeeper.connect::localhost:2181
key.serializer::org.apache.kafka.common.serialization.StringSerializer
source.topic::earth_to_curiosity_5
metadata.broker.list::localhost:9092
2017-12-23 13:00:19,182 [main] INFO space.exploration.mars.rover.sensor.Radar  - Radar configured:: 
2017-12-23 13:00:25,275 [main] INFO space.exploration.mars.rover.communication.Transmitter  - Sending information packet to curiosity_to_earth_5
2017-12-23 13:00:28,277 [pool-5-thread-1] INFO space.exploration.mars.rover.animation.SleepingAnimationEngine  - Rover is sleeping now
2017-12-23 13:00:46,795 [pool-7-thread-1] INFO space.exploration.mars.rover.power.BatteryMonitor  - BatteryMonitor performing due diligence. SCET = 1514055646795 Rover state = Sleeping State
2017-12-23 13:01:06,172 [pool-4-thread-1] INFO space.exploration.mars.rover.diagnostics.Pacemaker  - Diagnostics inhibited because rover is sleeping to conserve battery Current instructionQueue length = 0
2017-12-23 13:01:06,521 [Thread-2] INFO space.exploration.mars.rover.communication.Receiver  - Time Elapsed since last message = 49340
2017-12-23 13:01:06,604 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - Houston - this is curiosityActual.ephemerisTime: 5.25531368182699E8
stateCuriosity: -4.2160250007E7
stateCuriosity: -1.09828660087E8
stateCuriosity: -5.4435300905E7
stateCuriosity: 10.175
stateCuriosity: -12.66
stateCuriosity: -5.896
owltMSLEarth: 432.387
stateEarth: 4.2153404813E7
stateEarth: 1.09810829834E8
stateEarth: 5.442646306E7
stateEarth: -10.176
stateEarth: 12.652
stateEarth: 5.892
owltEarthMSL: 432.317
positionEarthWRTCuriosity: 4.2153404813E7
positionEarthWRTCuriosity: 1.09810829834E8
positionEarthWRTCuriosity: 5.442646306E7
owltEarthMSL2: 432.317
angSepHGAEarth: 156.976
utcTime: "2016-08-27~00:55:00"
sol: 1442
sclkValue: " 1/01442:19:08:25:84392"

2017-12-23 13:01:06,604 [Thread-2] INFO space.exploration.mars.rover.communication.Radio  - One Way Light Time computed by SPICE :: 432.387
2017-12-23 13:01:06,611 [Thread-2] INFO space.exploration.mars.rover.kernel.SleepingState  - Awaking from sleeping state
2017-12-23 13:01:06,611 [Thread-2] INFO space.exploration.mars.rover.animation.SleepingAnimationEngine  - Waking up rover
2017-12-23 13:01:06,613 [pool-9-thread-1] ERROR space.exploration.mars.rover.animation.SleepBreather  - Sleep animation interrupted.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at space.exploration.mars.rover.animation.SleepBreather.run(SleepBreather.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:01:09,623 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - timeStamp: 1514055666380
targets {
  roverModule: 8
  estimatedPowerUsage: 20
  action: "ClickCamera"
  roverSubModule: "RHAZ"
}

2017-12-23 13:01:15,653 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - 1514055675653,8,ClickCamera Current instructionQueue length = 0
2017-12-23 13:01:15,653 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - Rover Curiosity is going to try to take pictures!
2017-12-23 13:01:27,085 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - Houston - this is curiosityActual.ephemerisTime: 5.25532568182699E8
stateCuriosity: -4.2148030208E7
stateCuriosity: -1.09843841748E8
stateCuriosity: -5.4442374442E7
stateCuriosity: 10.191
stateCuriosity: -12.643
stateCuriosity: -5.894
owltMSLEarth: 432.427
stateEarth: 4.2141184154E7
stateEarth: 1.09826001917E8
stateEarth: 5.4433531976E7
stateEarth: -10.192
stateEarth: 12.635
stateEarth: 5.89
owltEarthMSL: 432.357
positionEarthWRTCuriosity: 4.2141184154E7
positionEarthWRTCuriosity: 1.09826001917E8
positionEarthWRTCuriosity: 5.4433531976E7
owltEarthMSL2: 432.357
angSepHGAEarth: 152.838
utcTime: "2016-08-27~01:16:00"
sol: 1442
sclkValue: " 1/01442:19:27:53:73707"

2017-12-23 13:01:27,085 [Thread-2] INFO space.exploration.mars.rover.communication.Radio  - One Way Light Time computed by SPICE :: 432.427
2017-12-23 13:01:27,098 [Thread-2] INFO space.exploration.mars.rover.communication.Transmitter  - Sending information packet to curiosity_to_earth_5
2017-12-23 13:01:30,100 [pool-7-thread-1] INFO space.exploration.mars.rover.power.BatteryMonitor  - BatteryMonitor performing due diligence. SCET = 1514055676795 Rover state = Listening State
2017-12-23 13:01:46,795 [pool-7-thread-1] INFO space.exploration.mars.rover.power.BatteryMonitor  - BatteryMonitor performing due diligence. SCET = 1514055706795 Rover state = Listening State
2017-12-23 13:01:50,287 [Thread-2] INFO space.exploration.mars.rover.communication.Receiver  - Time Elapsed since last message = 43766
2017-12-23 13:01:50,365 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - Houston - this is curiosityActual.ephemerisTime: 5.25534008182699E8
stateCuriosity: -4.2133341585E7
stateCuriosity: -1.09862032818E8
stateCuriosity: -5.4450858549E7
stateCuriosity: 10.209
stateCuriosity: -12.622
stateCuriosity: -5.89
owltMSLEarth: 432.474
stateEarth: 4.21264944E7
stateEarth: 1.09844181226E8
stateEarth: 5.4442010409E7
stateEarth: -10.21
stateEarth: 12.614
stateEarth: 5.886
owltEarthMSL: 432.404
positionEarthWRTCuriosity: 4.21264944E7
positionEarthWRTCuriosity: 1.09844181226E8
positionEarthWRTCuriosity: 5.4442010409E7
owltEarthMSL2: 432.404
angSepHGAEarth: 147.609
utcTime: "2016-08-27~01:39:00"
sol: 1442
sclkValue: " 1/01442:19:51:15:20886"

2017-12-23 13:01:50,365 [Thread-2] INFO space.exploration.mars.rover.communication.Radio  - One Way Light Time computed by SPICE :: 432.474
2017-12-23 13:01:50,373 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - timeStamp: 1514055710277
targets {
  roverModule: 6
  action: "Graceful Shutdown."
}

2017-12-23 13:01:56,387 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - 1514055716387,6,Graceful Shutdown. Current instructionQueue length = 0
2017-12-23 13:01:56,388 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - Rover initiating a gracefulShutdown.
2017-12-23 13:01:56,388 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - Synchronizing Clocks.
2017-12-23 13:01:56,388 [Thread-2] INFO space.exploration.mars.rover.kernel.SclkTimingState  - Synchronizing sclk and positionSensor to 2016-08-27~01:46:00
2017-12-23 13:01:56,388 [Thread-2] INFO space.exploration.mars.rover.kernel.SclkTimingState  - Houston, expect a diagnostics pause. Shutting down paceMaker
2017-12-23 13:01:56,388 [Thread-2] INFO space.exploration.mars.rover.diagnostics.Pacemaker  - Pacemaker diagnostic module interrupted.
2017-12-23 13:01:56,389 [Thread-2] INFO space.exploration.mars.rover.kernel.SclkTimingState  - Houston, be advised - garbageCollection is paused. Please wait before sending new signals.
2017-12-23 13:01:56,389 [Thread-2] INFO space.exploration.mars.rover.diagnostics.RoverGarbageCollector  - RoverGC interrupted
2017-12-23 13:01:56,389 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - UTCTime = 2016-08-27~01:46:00
2017-12-23 13:01:56,390 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Valid utc time ranges are dictated by clockService as follows:
2017-12-23 13:01:56,390 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - APPLICABLE_START_TIME=2000-001T11:58:55.816, APPLICABLE_STOP_TIME=2017-360T19:17:40.149
2017-12-23 13:01:56,390 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Given UTC = 2016-08-27~01:46:00
2017-12-23 13:01:56,391 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Please ensure that positionSensor and sclk are synchronized
2017-12-23 13:01:56,391 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - Synchronizing positionSensor clock to 2016-08-27~01:46:00
2017-12-23 13:01:56,392 [Thread-2] INFO space.exploration.mars.rover.kernel.SclkTimingState  - Restarting diagnostics heartbeat
2017-12-23 13:01:56,393 [Thread-2] INFO space.exploration.mars.rover.kernel.SclkTimingState  - Restarting garbageCollection
2017-12-23 13:01:56,393 [Thread-2] INFO space.exploration.mars.rover.diagnostics.RoverGarbageCollector  - Starting garbageCollection
2017-12-23 13:01:56,407 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Internal time::2016-08-27T01:47:00.000-05:00 sclk of::1/01442:19:58:03:97147
2017-12-23 13:02:02,477 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - Houston - this is curiosityActual.ephemerisTime: 5.25535268182699E8
stateCuriosity: -4.212046875E7
stateCuriosity: -1.09877925009E8
stateCuriosity: -5.4458276885E7
stateCuriosity: 10.224
stateCuriosity: -12.603
stateCuriosity: -5.885
owltMSLEarth: 432.516
stateEarth: 4.2113620509E7
stateEarth: 1.09860062951E8
stateEarth: 5.4449423695E7
stateEarth: -10.224
stateEarth: 12.595
stateEarth: 5.881
owltEarthMSL: 432.445
positionEarthWRTCuriosity: 4.2113620509E7
positionEarthWRTCuriosity: 1.09860062951E8
positionEarthWRTCuriosity: 5.4449423695E7
owltEarthMSL2: 432.445
angSepHGAEarth: 142.888
utcTime: "2016-08-27~02:00:00"
sol: 1442
sclkValue: " 1/01442:20:11:41:49668"

2017-12-23 13:02:02,477 [Thread-2] INFO space.exploration.mars.rover.communication.Radio  - One Way Light Time computed by SPICE :: 432.516
2017-12-23 13:02:02,485 [Thread-2] INFO space.exploration.mars.rover.communication.Transmitter  - Sending information packet to curiosity_to_earth_5
2017-12-23 13:02:05,486 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - Sending diagnostic heartbeat.
2017-12-23 13:02:05,557 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - Houston - this is curiosityActual.ephemerisTime: 5.25535628182698E8
stateCuriosity: -4.2116787594E7
stateCuriosity: -1.09882461252E8
stateCuriosity: -5.4460395303E7
stateCuriosity: 10.227
stateCuriosity: -12.598
stateCuriosity: -5.884
owltMSLEarth: 432.527
stateEarth: 4.2109939046E7
stateEarth: 1.09864596183E8
stateEarth: 5.4451540661E7
stateEarth: -10.228
stateEarth: 12.59
stateEarth: 5.88
owltEarthMSL: 432.457
positionEarthWRTCuriosity: 4.2109939046E7
positionEarthWRTCuriosity: 1.09864596183E8
positionEarthWRTCuriosity: 5.4451540661E7
owltEarthMSL2: 432.457
angSepHGAEarth: 141.521
utcTime: "2016-08-27~02:06:00"
sol: 1442
sclkValue: " 1/01442:20:17:31:86463"

2017-12-23 13:02:05,562 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - Internal time::2016-08-27T02:06:00.000-05:00 sclk of::1/01442:20:17:31:86463
2017-12-23 13:02:11,659 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - Houston - this is curiosityActual.ephemerisTime: 5.25536348182698E8
stateCuriosity: -4.2109421307E7
stateCuriosity: -1.09891527815E8
stateCuriosity: -5.4464630461E7
stateCuriosity: 10.235
stateCuriosity: -12.587
stateCuriosity: -5.881
owltMSLEarth: 432.551
stateEarth: 4.2102572135E7
stateEarth: 1.09873656705E8
stateEarth: 5.4455772904E7
stateEarth: -10.235
stateEarth: 12.579
stateEarth: 5.876
owltEarthMSL: 432.481
positionEarthWRTCuriosity: 4.2102572135E7
positionEarthWRTCuriosity: 1.09873656705E8
positionEarthWRTCuriosity: 5.4455772904E7
owltEarthMSL2: 432.481
angSepHGAEarth: 138.769
utcTime: "2016-08-27~02:18:00"
sol: 1442
sclkValue: " 1/01442:20:29:12:60052"

2017-12-23 13:02:11,659 [Thread-2] INFO space.exploration.mars.rover.communication.Radio  - One Way Light Time computed by SPICE :: 432.551
2017-12-23 13:02:11,667 [Thread-2] INFO space.exploration.mars.rover.communication.Transmitter  - Sending information packet to curiosity_to_earth_5
2017-12-23 13:02:14,667 [Thread-2] INFO space.exploration.mars.rover.kernel.ListeningState  - Severing ties with the rover.
2017-12-23 13:02:14,668 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  - Stopping all daemon processes.
2017-12-23 13:02:14,668 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  -  3.1 Stopping Pacemaker.
2017-12-23 13:02:14,668 [Thread-2] INFO space.exploration.mars.rover.diagnostics.Pacemaker  - Pacemaker diagnostic module shuttingDown.
2017-12-23 13:02:14,668 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  -  3.2 Stopping GarbageCollector.
2017-12-23 13:02:14,668 [Thread-2] INFO space.exploration.mars.rover.diagnostics.RoverGarbageCollector  - RoverGC shuttingDown.
2017-12-23 13:02:14,668 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  -  3.3 Stopping BatteryMonitor. 
2017-12-23 13:02:14,669 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  -  3.4. Stopping SleepMonitor. 
2017-12-23 13:02:14,669 [Thread-2] INFO space.exploration.mars.rover.diagnostics.SleepMonitor  - SleepMonitor is shuttingDown.
2017-12-23 13:02:14,669 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  -  3.5 Stopping PositionSensor.
2017-12-23 13:02:14,669 [Thread-2] INFO space.exploration.mars.rover.kernel.PositionSensor  - PositionSensor is shutting down.
2017-12-23 13:02:14,670 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  - 3.6. Saving properties file. 
2017-12-23 13:02:14,670 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  - Writing properties file to :: src/main/resources/marsConfig.properties
2017-12-23 13:02:14,671 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  -  3.7 Stopping SpacecraftClock. 
2017-12-23 13:02:14,671 [Thread-2] INFO space.exploration.mars.rover.kernel.SpacecraftClock  - SpacecraftClock shuttingDown.
2017-12-23 13:02:14,671 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  -  3.8 Shutting down graphics.
2017-12-23 13:02:14,684 [Thread-2] INFO space.exploration.mars.rover.kernel.Rover  - Houston this is Curiosity saying goodbye! Hope I did OK!
2017-12-23 13:02:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:03:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:04:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:05:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:06:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:07:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:08:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:09:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:10:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:11:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:12:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:13:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:14:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:15:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:16:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:17:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:18:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:19:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:20:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:21:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:22:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:23:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:24:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:25:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:26:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:27:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:28:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:29:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:30:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:31:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:32:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:33:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:34:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:35:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:36:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:37:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:38:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:39:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:40:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:41:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:42:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:43:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:44:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:45:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:46:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:47:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:48:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:49:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:50:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:51:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:52:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:53:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:54:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:55:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:56:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:57:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-23 13:58:56,393 [pool-12-thread-1] ERROR space.exploration.mars.rover.diagnostics.Pacemaker  - Encountered exception while generating diagnostic heartBeat. Its possible this instance is in a coverage gap for positionVectors.
java.lang.NullPointerException
	at space.exploration.mars.rover.diagnostics.Pacemaker.generateDiagnosticStatus(Pacemaker.java:112)
	at space.exploration.mars.rover.diagnostics.Pacemaker.sendHeartBeat(Pacemaker.java:53)
	at space.exploration.mars.rover.diagnostics.Pacemaker$Pulse.run(Pacemaker.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
